# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import json

def decode_payload(decoded_data):
    try:
        # Voltage
        byte_value = int(decoded_data[2:4], 16)
        voltage = byte_value / 1000

        # Credit
        credit_hex = decoded_data[10:14]
        reversed_hex = credit_hex[2:] + credit_hex[:2]
        credit = int(reversed_hex, 16) / 1000

        # Battery
        battery_hex = decoded_data[28:30]
        battery = int(battery_hex, 16) / 10

        return {
            "Voltage": f"{voltage:.3f} V",
            "Credit": f"{credit:.3f}",
            "Battery": f"{battery:.1f} V"
        }

    except Exception as e:
        return {"Error": str(e)}


def load_and_process(path):
    with open(path, "r") as f:
        data = json.load(f)

    decoded = data[0]["decoded_data"]
    return decode_payload(decoded)