# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import tkinter as tk
from tkinter import scrolledtext
from data_processor import load_and_process

DATA_PATH = "../data/sample_data.json"

class DemoGUI:

    def __init__(self, root):
        self.root = root
        self.root.title("Water Meter Monitoring Demo")
        self.root.geometry("600x400")

        self.title = tk.Label(
            root,
            text="Baylan Payload Demo",
            font=("Arial", 18, "bold")
        )
        self.title.pack(pady=10)

        self.text_area = scrolledtext.ScrolledText(
            root,
            width=60,
            height=15
        )
        self.text_area.pack()

        self.refresh_button = tk.Button(
            root,
            text="Load Data",
            command=self.load_data
        )
        self.refresh_button.pack(pady=10)

    def load_data(self):
        self.text_area.delete("1.0", tk.END)

        result = load_and_process(DATA_PATH)

        for k, v in result.items():
            self.text_area.insert(tk.END, f"{k}: {v}\n")


if __name__ == "__main__":
    root = tk.Tk()
    app = DemoGUI(root)
    root.mainloop()