# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import streamlit as st
import pandas as pd
from data_processor import load_and_process

DATA_PATH = "../data/sample_data.json"

st.set_page_config(page_title="Water Meter Dashboard", layout="wide")

st.title("💧 Live Water Meter Demo Dashboard")

if st.button("Refresh Data"):
    result = load_and_process(DATA_PATH)

    df = pd.DataFrame([result])

    st.subheader("Decoded Meter Data")
    st.dataframe(df)